import { Montserrat } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const montserratFont = Montserrat({
  variable: "--font-montserrat",
  subsets: ["cyrillic"],
});

const nanJaune = localFont({
  src: [
    {
      path: '../public/fonts/NaNJaune.ttf',
      weight: '600',
      style: 'normal',
    },
  ],
  variable: '--font-jaune'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserratFont.variable} ${nanJaune.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
